Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-09efc42336106d2f2
      Tags:
        - Key: "Name"
          Value: !Join ["-", [my, inst, cloudformation]]