Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-085f9c64a9b75eed5
      Tags:
        - Key: "Name"
          Value: !Join
            - " "
            - - "My Instance in"
              - !Ref AWS::Region
              